trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  JUICE_PORT: 3000

jobs:
  - job: JuiceShopLab
    displayName: 'Juice Shop + ZAP DAST'
    timeoutInMinutes: 59

    steps:

    - script: |
        docker pull bkimminich/juice-shop:latest
        docker run -d \
          --name juice-shop \
          -p $(JUICE_PORT):3000 \
          bkimminich/juice-shop:latest
        echo "Aguardando Juice Shop..."
        sleep 20
        curl -sf http://localhost:$(JUICE_PORT) > /dev/null && echo "Juice Shop UP" || exit 1
      displayName: 'Subir Juice Shop'

    - script: |
        docker run --rm \
          --network host \
          -v $(Build.ArtifactStagingDirectory):/zap/wrk:rw \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py \
            -t http://localhost:$(JUICE_PORT) \
            -r zap-report.html \
            -J zap-report.json \
            -I
      displayName: 'ZAP Baseline Scan'
      continueOnError: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'zap-reports'
        publishLocation: 'Container'
      displayName: 'Publicar relatório ZAP'
      condition: always()